#!bin/zsh

# Copy/move/remove
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -Iv"

# Diff
alias diff="diff --color=auto"

# Greps
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias grep="grep --color=auto"

# Directories
alias mkd="mkdir -pv"

# Info
alias info="info --vi-keys"

# LESS
alias less="less --use-color -Dsm"

# LS
alias ls="ls --color=auto --group-directories-first"
alias ll="ls -alF"
alias ld="ls -ald"
alias la="ls -A"
alias l="ls -CF"

# Neovim
alias vi="nvim"

# Sudo
alias sudo="sudo "

# Vifm
alias far="tmux neww -n 'far' vifm"

# Zathura
alias za="zathura --fork 2>/dev/null"
