#!bin/zsh
# Neovim
alias vi="nvim"

# Sudo
alias sudo="sudo "

# LS
alias ls="ls --color=auto --group-directories-first"
alias ll="ls -alF"
alias ld="ls -ald"
alias la="ls -A"
alias l="ls -CF"

# Greps
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

# Diff
alias diff="diff --color=auto"

# Move/remove/copy
alias mv="mv -iv"
alias cp="cp -iv"
alias rm="rm -Iv"

# Directories
alias mkd="mkdir -pv"

# Md book
alias bkb="mdbook build"
alias bkc="mdbook clean"
alias bks="mdbook serve -o"

# Tmux/tmuxinator
alias tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
alias tfs="tmuxinator_fzf_start "
alias session="tmux_sessionizer"

# LF in 2 tmux panes
alias lflf="tmux neww -n 'commander' lf \; splitw -h lf \; selectp -L"

# LESS
alias less="less --use-color -Dsm"

# Info
alias info="info --vi-keys"
