[colors.cursor]
cursor = "#ebdbb2"
text = "#282828"

[colors.dim]
black = "#1c1c1c"
blue = "#5f87af"
cyan = "#5f8787"
green = "#87af87"
magenta = "#af87af"
red = "#d75f5f"
white = "#9e9e9e"
yellow = "#afaf87"

[colors.primary]
background = "#1c1c1c"
foreground = "#bcbcbc"

[cursor]
style = "Beam"

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mode = "~Alt"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mode = "~Alt"
mods = "Control|Alt|Shift"

[scrolling]
history = 10000

[window]
decorations = "full"
startup_mode = "Maximized"
